#!/usr/bin/env bash

killall xidlehook

# Run xidlehook
xidlehook \
  `# Don't lock when there's a fullscreen application` \
  --not-when-fullscreen \
  `# Don't lock when there's audio playing` \
  --not-when-audio \
  --timer 870 \
    'notify-send -t 30000 "Vérouillage dans 30s"' \
    '' \
    --timer 30 \
    '~/.config/i3/scripts/blur-lock' \
    '' \
  --timer 300 \
    'systemctl suspend' \
    '' \
  &

