#!/bin/zsh

player_status=$(playerctl status 2> /dev/null)
if [[ $? -eq 0 ]]; then
    if [[ $player_status = "Playing" || $player_status = "Paused" ]]
    then
        metadata="$(playerctl metadata artist) - $(playerctl metadata title)"
    fi
fi

# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]
then
    echo "%{F#89a1e2}$metadata%{F-}"
elif [[ $player_status = "Paused" ]]
then
    echo "%{F#545d89}$metadata%{F-}"
else
    echo ""
fi
